import Head from 'next/head'
import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Header from '../components/Header';
import { useState } from 'react';

export enum Tabs {
  INFORMACAO ='Informação',
  RESPOSTA = 'Resposta ao Convite',
};

export default function App({ Component, pageProps }: AppProps) {
  const [tabSelected, setTabSelected] = useState<Tabs>(Tabs.INFORMACAO);

  return (
    <>
      <Head>
        <title>Casamento Débora e Xavier</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/WeddingFavicon.ico" />
      </Head>
      <Header tabSelected={tabSelected} setTabSelected={setTabSelected} />
      <Component tabSelected={tabSelected} {...pageProps} />
    </>
  )}
